# Notes:
# This is not finished, could be changed to work with multiple OSs, use existing modules from ansible-galaxy if applicable
# When tested and working it would start a new EC2 server,
# then install and enable docker
#
# http://docs.ansible.com/ansible/latest/ec2_module.html
#
# EC2 Ansible external inventory script
# http://docs.ansible.com/ansible/latest/intro_dynamic_inventory.html#example-aws-ec2-external-inventory-script
# set keys before calling, in order to use it e.g.
# export AWS_ACCESS_KEY_ID='AK123'
# export AWS_SECRET_ACCESS_KEY='abc123'
# then
# ansible-playbook -i ec2.py ansible-aws.yml
# narrow down runs with tags e.g. tag_Name_thedockerbox

- name: Create EC2 host
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Provision Docker host
      ec2:
         group: some_sg
         instance_type: t2.micro
         image: "some_AMI_ID (centos)"
         wait: true
         exact_count: 1
         instance_tags:
            Name: thedockerbox
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

- name: Configure Docker
  hosts: launched
  become: True
  gather_facts: True

  tasks:

    - name: Install docker and docker-compose
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - docker
        - docker-compose

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Make directory for files
      file:
        path: "/opt/jamesp"
        state: directory

    - name: Copy docker-compose files and folders
      copy:
        src: "{{ item }}"
        dest: "/opt/jamesp/{{ item }}"
      with_items:
        - "docker-compose.yml"
        - mariadb
        - prometheus
        - wordpress

    - name: Start up services with docker_service
      docker_service:
       project_src: "/opt/jamesp"
       build: yes
