version: '2'

services:

  wordpress:
    build: wordpress/
    # image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: james

  mysql:
    # image: mariadb
    build: mariadb/
    environment:
      MYSQL_ROOT_PASSWORD: james

  prometheus:
    #image: prom/prometheus
    build: prometheus/
    ports:
      - 9090:9090
